srun: ROUTE: split_hostlist: hl=bun005 tree_width 0
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
wandb: Currently logged in as: rodxiang2. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.17.0
wandb: Run data is saved locally in /home/s4642506/TACO/exp_local/default/wandb/run-20240520_181953-1wv0p278
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run TACO_cartpole_swingup_run_seed_1
wandb: ‚≠êÔ∏è View project at https://wandb.ai/rodxiang2/visualRL
wandb: üöÄ View run at https://wandb.ai/rodxiang2/visualRL/runs/1wv0p278
Error executing job with overrides: ['agent=taco', 'task=cartpole_swingup', 'seed=1']
Traceback (most recent call last):
  File "./train.py", line 211, in main
    workspace.train()
  File "/home/s4642506/TACO/train.py", line 176, in train
    metrics = self.agent.update(self.replay_iter, self.global_step)
  File "/home/s4642506/TACO/agents/taco.py", line 356, in update
    batch = next(replay_iter)
  File "/home/s4642506/.conda/envs/taco/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/s4642506/.conda/envs/taco/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/s4642506/.conda/envs/taco/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/s4642506/.conda/envs/taco/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/s4642506/.conda/envs/taco/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/s4642506/.conda/envs/taco/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 40, in fetch
    return self.collate_fn(data)
  File "/home/s4642506/.conda/envs/taco/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/s4642506/.conda/envs/taco/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/s4642506/.conda/envs/taco/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/home/s4642506/.conda/envs/taco/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1] at entry 0 and [6] at entry 3


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
wandb: - 0.027 MB of 0.027 MB uploadedwandb: \ 0.027 MB of 0.038 MB uploadedwandb: | 0.040 MB of 0.040 MB uploadedwandb: 
wandb: Run history:
wandb:        eval/episode ‚ñÅ
wandb: eval/episode_length ‚ñÅ
wandb: eval/episode_reward ‚ñÅ
wandb:           eval/step ‚ñÅ
wandb:     eval_total_time ‚ñÅ
wandb: 
wandb: Run summary:
wandb:        eval/episode 0
wandb: eval/episode_length 1000.0
wandb: eval/episode_reward 6.93137
wandb:           eval/step 0
wandb:     eval_total_time 0.01886
wandb: 
wandb: üöÄ View run TACO_cartpole_swingup_run_seed_1 at: https://wandb.ai/rodxiang2/visualRL/runs/1wv0p278
wandb: ‚≠êÔ∏è View project at: https://wandb.ai/rodxiang2/visualRL
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240520_181953-1wv0p278/logs
srun: error: bun005: task 0: Exited with exit code 1
